# Generated by Django 4.1.5 on 2023-03-23 17:30

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dni_num', models.IntegerField(verbose_name='N° DNI')),
                ('ap_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('ap_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombres')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=2, verbose_name='Sexo')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento (dd/MM/AAAA)')),
                ('departamento', models.CharField(max_length=80, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('distrito', models.CharField(max_length=150, verbose_name='Distrito')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('inst_procedencia', models.CharField(max_length=150, verbose_name='Colegio de Procedencia')),
                ('egreso', models.IntegerField(verbose_name='Año de egreso')),
                ('celular', models.IntegerField(verbose_name='N° Celular')),
                ('carrera', models.CharField(choices=[('CC', 'Contrucción Civil'), ('C', 'Contabilidad'), ('EM', 'Explotación Minera')], max_length=2, verbose_name='Primera opcion Programa de Estudios al que postula')),
                ('seg_carrera', models.CharField(choices=[('CC', 'Contrucción Civil'), ('C', 'Contabilidad'), ('EM', 'Explotación Minera')], max_length=2, verbose_name='Segunda Opcion Programa de Estudios al que postula')),
                ('foto', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps/', verbose_name='Foto')),
                ('dni', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps/', verbose_name='Foto DNI')),
                ('certificado', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps/', verbose_name='Certificado de Estudios')),
                ('num_operacion', models.IntegerField(unique=True, verbose_name='N° Operación Voucher')),
                ('voucher', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps/', verbose_name='Voucher')),
                ('dec_juarada', models.BooleanField(default=False, verbose_name='Declaro bajo juramento que los datos que consigno en la presente FICHA DE INSCRIPCIÓN, son verídicos y me remito para la confrontación con los documentos originales. De no ser correctos pierdo la vacante de admisión y renuncio a todo derecho que pueda obtener.')),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
            },
        ),
    ]
