# Generated by Django 4.1.5 on 2023-03-26 20:35

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('admisions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='certificado',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps', verbose_name='Certificado de Estudios'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='dni_num',
            field=models.IntegerField(unique=True, verbose_name='N° DNI'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='num_operacion',
            field=models.CharField(max_length=20, unique=True, verbose_name='N° Operación Voucher'),
        ),
    ]
