# Generated by Django 4.1.5 on 2023-03-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisions', '0002_alter_postulante_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='fecha_nac',
            field=models.DateField(blank=True, verbose_name='Fecha de Nacimiento (dd/MM/AAAA)'),
        ),
    ]
