# Generated by Django 4.1.5 on 2023-03-27 04:28

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('admisions', '0005_alter_postulante_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='certificado',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps', verbose_name='FotoCertificado de Estudios'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='sexo',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=2, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='voucher',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='maps/', verbose_name='Foto Voucher'),
        ),
    ]
