# Generated by Django 4.1.5 on 2023-03-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisions', '0006_alter_postulante_certificado_alter_postulante_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='num_operacion',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cod. Voucher'),
        ),
    ]
